package it.polimi.ingsw.network;

public enum MessageType {
    ERROR,
    NICKNAME,

    GAMENAME,
    MENU_OPTION,
    NUM_OF_PLAYERS,
    NUM_OF_PLAYERS_REQUEST,
    TILE_POSITION,
    BOOKSHELF_COLUMN,
    SWITCH_PHASE,
    BOARD,
    BOOKSHELF,
    JOIN_GAME_REQUEST,
    TILE_PACK,
    PERSONAL_GOAL_CARD,
    COMMON_GOAL_CARD,
    SCORE,
    END_GAME,
    INSERTION_REQUEST,
    ITEM_TILE_INDEX, CREATOR_NICKNAME,


    // error


}
