package it.polimi.ingsw.network;

public enum MessageType {
    ERROR,
    NICKNAME,
    GAME_NAME,
    MENU_OPTION,
    GAME_CREATION,
    GAME_CHOICE,
    NUM_OF_PLAYERS_REQUEST,
    TILE_POSITION,
    BOOKSHELF_COLUMN,
    END_TURN,
    BOARD,
    BOOKSHELF,
    JOIN_GAME_REQUEST,
    PLAYER_TURN,
    TILE_PACK,
    PERSONAL_GOAL_CARD,
    COMMON_GOAL_CARD,
    LAST_TURN,
    END_GAME,
    INSERTION_REQUEST,
    SCORE,
    ITEM_TILE_INDEX, CREATOR_NICKNAME, FILL_BOOSHELF,
    // error


}
